; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
; Non-commercial use only

#define MyAppName "Українізатор для Microsoft Flight Simulator 2024"
#define MyAppVersion "1.0"
#define MyAppPublisher "romamakar"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{7EA849E8-7C92-4D94-9DC0-CFE1BF803D4D}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
DefaultDirName={pf32}\Steam\steamapps\common\Microsoft Flight Simulator 2024
DisableDirPage=no
DisableWelcomePage=no
;DefaultGroupName={#MyAppName}
; Uncomment the following line to run in non administrative install mode (install for current user only).
;PrivilegesRequired=lowest
OutputBaseFilename=MSFS2024Ukr_ru
OutputDir=Output
SetupIconFile=D:\a\MSFS2024Ukr\MSFS2024Ukr\installer\installer.ico
SolidCompression=yes
WizardStyle=modern dynamic

[Messages]
WelcomeLabel1=Вітаємо в майстрі встановлення {#MyAppName}!
WelcomeLabel2=Ця версія української локалізації для гри Microsoft Flight Simulator 2024. %n%nУ грі виберіть кацапську мову, щоб отримати українську локалізацію. %n%n Гра постійно оновлюється, тому періодично рекомендується перевстановлювати локалізацію з https://github.com/romamakar/MSFS2024Ukr/releases/tag/exe %n%nВсе буде Україна!


[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"
Name: "ukrainian"; MessagesFile: "compiler:Languages\Ukrainian.isl"

[Files]
Source: "D:\a\MSFS2024Ukr\MSFS2024Ukr\MSFS2024Ukr\bin\Release\net8.0\MSFS2024ukr-ru\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Run]
Filename:"{app}\FlightSimulator2024.exe"; Description:"Запустити Microsoft Flight Simulator 2024"; Flags: postinstall nowait shellexec

